export enum StorageDeliveryError {
  ALREADY_EXISTS = '400: Storage delivery already exists',
  ALREADY_EXPIRED = '400: Storage delivery already expired',
  NOT_CREATED = '400: Storage delivery is not created',
  NOT_TAKEN = '400: Storage delivery is not taken',
  NOT_EXECUTED = '400: Storage delivery is not executed',
  NOT_COMPLETED = '400: Storage delivery is not completed',
  NOT_CUSTOMER = '403: You are not storage delivery customer',
  NOT_EXECUTOR = '403: You are not storage delivery executor',
  CREATE_FAILED = '500: Failed to create storage delivery',
  EDIT_FAILED = '500: Failed to edit storage delivery',
  TAKE_FAILED = '500: Failed to take storage delivery',
  UNTAKE_FAILED = '500: Failed to untake storage delivery',
  EXECUTE_FAILED = '500: Failed to execute storage delivery',
  COMPLETE_FAILED = '500: Failed to complete storage delivery',
  DELETE_FAILED = '500: Failed to delete storage delivery',
  RATE_FAILED = '500: Failed to rate storage delivery',
}
