export const items = [
  '02: Stone',
  '02: Granite',
  '0: Polished Granite',
  '02: Diorite',
  '0: Polished Diorite',
  '02: Andesite',
  '0: Polished Andesite',
  '02: Deepslate',
  '0: Cobbled Deepslate',
  '0: Polished Deepslate',
  '2: Calcite',
  '2: Tuff',
  '2: Dripstone Block',
  '2: Grass Block',
  '2: Dirt',
  '2: Coarse Dirt',
  '2: Podzol',
  '2: Rooted Dirt',
  '2: Mud',
  '2: Crimson Nylium',
  '2: Warped Nylium',
  '0: Cobblestone',
  '0: Oak Planks',
  '0: Spruce Planks',
  '0: Birch Planks',
  '0: Jungle Planks',
  '0: Acacia Planks',
  '0: Cherry Planks',
  '0: Dark Oak Planks',
  '0: Mangrove Planks',
  '0: Bamboo Planks',
  '0: Crimson Planks',
  '0: Warped Planks',
  '0: Bamboo Mosaic',
  '2: Oak Sapling',
  '2: Spruce Sapling',
  '2: Birch Sapling',
  '2: Jungle Sapling',
  '2: Acacia Sapling',
  '2: Cherry Sapling',
  '2: Dark Oak Sapling',
  '2: Mangrove Propagule',
  '2: Bedrock',
  '2: Sand',
  '3: Suspicious Sand',
  '3: Suspicious Gravel',
  '2: Red Sand',
  '2: Gravel',
  '2: Coal Ore',
  '2: Deepslate Coal Ore',
  '2: Iron Ore',
  '2: Deepslate Iron Ore',
  '2: Copper Ore',
  '2: Deepslate Copper Ore',
  '2: Gold Ore',
  '2: Deepslate Gold Ore',
  '24: Redstone Ore',
  '2: Deepslate Redstone Ore',
  '2: Emerald Ore',
  '2: Deepslate Emerald Ore',
  '2: Lapis Ore',
  '2: Deepslate Lapis Ore',
  '2: Diamond Ore',
  '2: Deepslate Diamond Ore',
  '2: Nether Gold Ore',
  '2: Nether Quartz Ore',
  '28: Ancient Debris',
  '0: Coal Block',
  '2: Raw Iron Block',
  '2: Raw Copper Block',
  '2: Raw Gold Block',
  '024: Amethyst Block',
  '2: Budding Amethyst',
  '0: Iron Block',
  '0: Copper Block',
  '0: Gold Block',
  '0: Diamond Block',
  '0: Netherite Block',
  '0: Exposed Copper',
  '0: Weathered Copper',
  '0: Oxidized Copper',
  '0: Cut Copper',
  '0: Exposed Cut Copper',
  '0: Weathered Cut Copper',
  '0: Oxidized Cut Copper',
  '0: Cut Copper Stairs',
  '0: Exposed Cut Copper Stairs',
  '0: Weathered Cut Copper Stairs',
  '0: Oxidized Cut Copper Stairs',
  '0: Cut Copper Slab',
  '0: Exposed Cut Copper Slab',
  '0: Weathered Cut Copper Slab',
  '0: Oxidized Cut Copper Slab',
  '0: Waxed Copper Block',
  '0: Waxed Exposed Copper',
  '0: Waxed Weathered Copper',
  '0: Waxed Oxidized Copper',
  '0: Waxed Cut Copper',
  '0: Waxed Exposed Cut Copper',
  '0: Waxed Weathered Cut Copper',
  '0: Waxed Oxidized Cut Copper',
  '0: Waxed Cut Copper Stairs',
  '0: Waxed Exposed Cut Copper Stairs',
  '0: Waxed Weathered Cut Copper Stairs',
  '0: Waxed Oxidized Cut Copper Stairs',
  '0: Waxed Cut Copper Slab',
  '0: Waxed Exposed Cut Copper Slab',
  '0: Waxed Weathered Cut Copper Slab',
  '0: Waxed Oxidized Cut Copper Slab',
  '02: Oak Log',
  '02: Spruce Log',
  '02: Birch Log',
  '02: Jungle Log',
  '02: Acacia Log',
  '02: Cherry Log',
  '02: Dark Oak Log',
  '02: Mangrove Log',
  '2: Mangrove Roots',
  '2: Muddy Mangrove Roots',
  '02: Crimson Stem',
  '02: Warped Stem',
  '0: Bamboo Block',
  '0: Stripped Oak Log',
  '0: Stripped Spruce Log',
  '0: Stripped Birch Log',
  '0: Stripped Jungle Log',
  '0: Stripped Acacia Log',
  '0: Stripped Cherry Log',
  '0: Stripped Dark Oak Log',
  '0: Stripped Mangrove Log',
  '0: Stripped Crimson Stem',
  '0: Stripped Warped Stem',
  '0: Stripped Oak Wood',
  '0: Stripped Spruce Wood',
  '0: Stripped Birch Wood',
  '0: Stripped Jungle Wood',
  '0: Stripped Acacia Wood',
  '0: Stripped Cherry Wood',
  '0: Stripped Dark Oak Wood',
  '0: Stripped Mangrove Wood',
  '0: Stripped Crimson Hyphae',
  '0: Stripped Warped Hyphae',
  '0: Stripped Bamboo Block',
  '0: Oak Wood',
  '0: Spruce Wood',
  '0: Birch Wood',
  '0: Jungle Wood',
  '0: Acacia Wood',
  '0: Cherry Wood',
  '0: Dark Oak Wood',
  '0: Mangrove Wood',
  '0: Crimson Hyphae',
  '0: Warped Hyphae',
  '2: Oak Leaves',
  '2: Spruce Leaves',
  '2: Birch Leaves',
  '2: Jungle Leaves',
  '2: Acacia Leaves',
  '2: Cherry Leaves',
  '2: Dark Oak Leaves',
  '2: Mangrove Leaves',
  '2: Azalea Leaves',
  '2: Flowering Azalea Leaves',
  '2: Sponge',
  '2: Wet Sponge',
  '1: Glass',
  '13: Tinted Glass',
  '0: Lapis Block',
  '02: Sandstone',
  '0: Chiseled Sandstone',
  '0: Cut Sandstone',
  '2: Cobweb',
  '2: Grass',
  '2: Fern',
  '2: Azalea',
  '2: Flowering Azalea',
  '2: Dead Bush',
  '2: Seagrass',
  '2: Sea Pickle',
  '14: White Wool',
  '1: Orange Wool',
  '1: Magenta Wool',
  '1: Light Blue Wool',
  '1: Yellow Wool',
  '1: Lime Wool',
  '1: Pink Wool',
  '1: Gray Wool',
  '1: Light Gray Wool',
  '1: Cyan Wool',
  '1: Purple Wool',
  '1: Blue Wool',
  '1: Brown Wool',
  '1: Green Wool',
  '1: Red Wool',
  '1: Black Wool',
  '2: Dandelion',
  '2: Poppy',
  '2: Blue Orchid',
  '2: Allium',
  '2: Azure Bluet',
  '2: Red Tulip',
  '2: Orange Tulip',
  '2: White Tulip',
  '2: Pink Tulip',
  '2: Oxeye Daisy',
  '2: Cornflower',
  '2: Lily of The Valley',
  '2: Wither Rose',
  '2: Torchflower',
  '2: Pitcher Plant',
  '2: Spore Blossom',
  '2: Brown Mushroom',
  '2: Red Mushroom',
  '2: Crimson Fungus',
  '2: Warped Fungus',
  '2: Crimson Roots',
  '2: Warped Roots',
  '2: Nether Sprouts',
  '2: Weeping Vines',
  '2: Twisting Vines',
  '2: Sugar Cane',
  '2: Kelp',
  '2: Moss Carpet',
  '2: Pink Petals',
  '2: Moss Block',
  '2: Hanging Roots',
  '24: Big Dripleaf',
  '2: Small Dripleaf',
  '2: Bamboo',
  '0: Oak Slab',
  '0: Spruce Slab',
  '0: Birch Slab',
  '0: Jungle Slab',
  '0: Acacia Slab',
  '0: Cherry Slab',
  '0: Dark Oak Slab',
  '0: Mangrove Slab',
  '0: Bamboo Slab',
  '0: Bamboo Mosaic Slab',
  '0: Crimson Slab',
  '0: Warped Slab',
  '0: Stone Slab',
  '0: Smooth Stone Slab',
  '0: Sandstone Slab',
  '0: Cut Sandstone Slab',
  ': Petrified Oak Slab',
  '0: Cobblestone Slab',
  '0: Brick Slab',
  '0: Stone Brick Slab',
  '0: Mud Brick Slab',
  '0: Nether Brick Slab',
  '0: Quartz Slab',
  '0: Red Sandstone Slab',
  '0: Cut Red Sandstone Slab',
  '0: Purpur Slab',
  '0: Prismarine Slab',
  '0: Prismarine Brick Slab',
  '0: Dark Prismarine Slab',
  '0: Smooth Quartz',
  '0: Smooth Red Sandstone',
  '0: Smooth Sandstone',
  '0: Smooth Stone',
  '0: Bricks',
  '3: Bookshelf',
  '34: Chiseled Bookshelf',
  '3: Decorated Pot',
  '0: Mossy Cobblestone',
  '2: Obsidian',
  '3: Torch',
  '3: End Rod',
  '2: Chorus Plant',
  '2: Chorus Flower',
  '0: Purpur Block',
  '0: Purpur Pillar',
  '0: Purpur Stairs',
  ': Spawner',
  '34: Chest',
  '3: Crafting Table',
  '2: Farmland',
  '34: Furnace',
  '3: Ladder',
  '0: Cobblestone Stairs',
  '2: Snow',
  '2: Ice',
  '2: Snow Block',
  '2: Cactus',
  '2: Clay',
  '34: Jukebox',
  '0: Oak Fence',
  '0: Spruce Fence',
  '0: Birch Fence',
  '0: Jungle Fence',
  '0: Acacia Fence',
  '0: Cherry Fence',
  '0: Dark Oak Fence',
  '0: Mangrove Fence',
  '0: Bamboo Fence',
  '0: Crimson Fence',
  '0: Warped Fence',
  '2: Pumpkin',
  '2: Carved Pumpkin',
  '2: Jack O Lantern',
  '02: Netherrack',
  '2: Soul Sand',
  '2: Soul Soil',
  '02: Basalt',
  '0: Polished Basalt',
  '02: Smooth Basalt',
  '3: Soul Torch',
  '23: Glowstone',
  '3: Infested Stone',
  '3: Infested Cobblestone',
  '3: Infested Stone Bricks',
  '3: Infested Mossy Stone Bricks',
  '3: Infested Cracked Stone Bricks',
  '3: Infested Chiseled Stone Bricks',
  '3: Infested Deepslate',
  '0: Stone Bricks',
  '0: Mossy Stone Bricks',
  '0: Cracked Stone Bricks',
  '0: Chiseled Stone Bricks',
  '0: Packed Mud',
  '0: Mud Bricks',
  '0: Deepslate Bricks',
  '0: Cracked Deepslate Bricks',
  '0: Deepslate Tiles',
  '0: Cracked Deepslate Tiles',
  '0: Chiseled Deepslate',
  '0: Reinforced Deepslate',
  '2: Brown Mushroom Block',
  '2: Red Mushroom Block',
  '2: Mushroom Stem',
  '0: Iron Bars',
  '03: Chain',
  '1: Glass Pane',
  '2: Melon',
  '2: Vine',
  '23: Glow Lichen',
  '0: Brick Stairs',
  '0: Stone Brick Stairs',
  '0: Mud Brick Stairs',
  '2: Mycelium',
  '2: Lily Pad',
  '0: Nether Bricks',
  '0: Cracked Nether Bricks',
  '0: Chiseled Nether Bricks',
  '0: Nether Brick Fence',
  '0: Nether Brick Stairs',
  '2: Sculk',
  '2: Sculk Vein',
  '2: Sculk Catalyst',
  '24: Sculk Shrieker',
  '3: Enchanting Table',
  '3: End Portal Frame',
  '02: End Stone',
  '0: End Stone Bricks',
  ': Dragon Egg',
  '0: Sandstone Stairs',
  '3: Ender Chest',
  '0: Emerald Block',
  '0: Oak Stairs',
  '0: Spruce Stairs',
  '0: Birch Stairs',
  '0: Jungle Stairs',
  '0: Acacia Stairs',
  '0: Cherry Stairs',
  '0: Dark Oak Stairs',
  '0: Mangrove Stairs',
  '0: Bamboo Stairs',
  '0: Bamboo Mosaic Stairs',
  '0: Crimson Stairs',
  '0: Warped Stairs',
  ': Command Block',
  '3: Beacon',
  '0: Cobblestone Wall',
  '0: Mossy Cobblestone Wall',
  '0: Brick Wall',
  '0: Prismarine Wall',
  '0: Red Sandstone Wall',
  '0: Mossy Stone Brick Wall',
  '0: Granite Wall',
  '0: Stone Brick Wall',
  '0: Mud Brick Wall',
  '0: Nether Brick Wall',
  '0: Andesite Wall',
  '0: Red Nether Brick Wall',
  '0: Sandstone Wall',
  '0: End Stone Brick Wall',
  '0: Diorite Wall',
  '0: Blackstone Wall',
  '0: Polished Blackstone Wall',
  '0: Polished Blackstone Brick Wall',
  '0: Cobbled Deepslate Wall',
  '0: Polished Deepslate Wall',
  '0: Deepslate Brick Wall',
  '0: Deepslate Tile Wall',
  '3: Anvil',
  '3: Chipped Anvil',
  '3: Damaged Anvil',
  '0: Chiseled Quartz Block',
  '0: Quartz Block',
  '0: Quartz Bricks',
  '0: Quartz Pillar',
  '0: Quartz Stairs',
  '1: White Terracotta',
  '1: Orange Terracotta',
  '1: Magenta Terracotta',
  '1: Light Blue Terracotta',
  '1: Yellow Terracotta',
  '1: Lime Terracotta',
  '1: Pink Terracotta',
  '1: Gray Terracotta',
  '1: Light Gray Terracotta',
  '1: Cyan Terracotta',
  '1: Purple Terracotta',
  '1: Blue Terracotta',
  '1: Brown Terracotta',
  '1: Green Terracotta',
  '1: Red Terracotta',
  '1: Black Terracotta',
  ': Barrier',
  ': Light',
  '2: Hay Block',
  '1: White Carpet',
  '1: Orange Carpet',
  '1: Magenta Carpet',
  '1: Light Blue Carpet',
  '1: Yellow Carpet',
  '1: Lime Carpet',
  '1: Pink Carpet',
  '1: Gray Carpet',
  '1: Light Gray Carpet',
  '1: Cyan Carpet',
  '1: Purple Carpet',
  '1: Blue Carpet',
  '1: Brown Carpet',
  '1: Green Carpet',
  '1: Red Carpet',
  '1: Black Carpet',
  '1: Terracotta',
  '2: Packed Ice',
  '2: Dirt Path',
  '2: Sunflower',
  '2: Lilac',
  '2: Rose Bush',
  '2: Peony',
  '2: Tall Grass',
  '2: Large Fern',
  '1: White Stained Glass',
  '1: Orange Stained Glass',
  '1: Magenta Stained Glass',
  '1: Light Blue Stained Glass',
  '1: Yellow Stained Glass',
  '1: Lime Stained Glass',
  '1: Pink Stained Glass',
  '1: Gray Stained Glass',
  '1: Light Gray Stained Glass',
  '1: Cyan Stained Glass',
  '1: Purple Stained Glass',
  '1: Blue Stained Glass',
  '1: Brown Stained Glass',
  '1: Green Stained Glass',
  '1: Red Stained Glass',
  '1: Black Stained Glass',
  '1: White Stained Glass Pane',
  '1: Orange Stained Glass Pane',
  '1: Magenta Stained Glass Pane',
  '1: Light Blue Stained Glass Pane',
  '1: Yellow Stained Glass Pane',
  '1: Lime Stained Glass Pane',
  '1: Pink Stained Glass Pane',
  '1: Gray Stained Glass Pane',
  '1: Light Gray Stained Glass Pane',
  '1: Cyan Stained Glass Pane',
  '1: Purple Stained Glass Pane',
  '1: Blue Stained Glass Pane',
  '1: Brown Stained Glass Pane',
  '1: Green Stained Glass Pane',
  '1: Red Stained Glass Pane',
  '1: Black Stained Glass Pane',
  '02: Prismarine',
  '0: Prismarine Bricks',
  '0: Dark Prismarine',
  '0: Prismarine Stairs',
  '0: Prismarine Brick Stairs',
  '0: Dark Prismarine Stairs',
  '03: Sea Lantern',
  '02: Red Sandstone',
  '0: Chiseled Red Sandstone',
  '0: Cut Red Sandstone',
  '0: Red Sandstone Stairs',
  ': Repeating Command Block',
  ': Chain Command Block',
  '23: Magma Block',
  '2: Nether Wart Block',
  '2: Warped Wart Block',
  '0: Red Nether Bricks',
  '2: Bone Block',
  ': Structure Void',
  '13: Shulker Box',
  '13: White Shulker Box',
  '13: Orange Shulker Box',
  '13: Magenta Shulker Box',
  '13: Light Blue Shulker Box',
  '13: Yellow Shulker Box',
  '13: Lime Shulker Box',
  '13: Pink Shulker Box',
  '13: Gray Shulker Box',
  '13: Light Gray Shulker Box',
  '13: Cyan Shulker Box',
  '13: Purple Shulker Box',
  '13: Blue Shulker Box',
  '13: Brown Shulker Box',
  '13: Green Shulker Box',
  '13: Red Shulker Box',
  '13: Black Shulker Box',
  '1: White Glazed Terracotta',
  '1: Orange Glazed Terracotta',
  '1: Magenta Glazed Terracotta',
  '1: Light Blue Glazed Terracotta',
  '1: Yellow Glazed Terracotta',
  '1: Lime Glazed Terracotta',
  '1: Pink Glazed Terracotta',
  '1: Gray Glazed Terracotta',
  '1: Light Gray Glazed Terracotta',
  '1: Cyan Glazed Terracotta',
  '1: Purple Glazed Terracotta',
  '1: Blue Glazed Terracotta',
  '1: Brown Glazed Terracotta',
  '1: Green Glazed Terracotta',
  '1: Red Glazed Terracotta',
  '1: Black Glazed Terracotta',
  '1: White Concrete',
  '1: Orange Concrete',
  '1: Magenta Concrete',
  '1: Light Blue Concrete',
  '1: Yellow Concrete',
  '1: Lime Concrete',
  '1: Pink Concrete',
  '1: Gray Concrete',
  '1: Light Gray Concrete',
  '1: Cyan Concrete',
  '1: Purple Concrete',
  '1: Blue Concrete',
  '1: Brown Concrete',
  '1: Green Concrete',
  '1: Red Concrete',
  '1: Black Concrete',
  '1: White Concrete Powder',
  '1: Orange Concrete Powder',
  '1: Magenta Concrete Powder',
  '1: Light Blue Concrete Powder',
  '1: Yellow Concrete Powder',
  '1: Lime Concrete Powder',
  '1: Pink Concrete Powder',
  '1: Gray Concrete Powder',
  '1: Light Gray Concrete Powder',
  '1: Cyan Concrete Powder',
  '1: Purple Concrete Powder',
  '1: Blue Concrete Powder',
  '1: Brown Concrete Powder',
  '1: Green Concrete Powder',
  '1: Red Concrete Powder',
  '1: Black Concrete Powder',
  '2: Turtle Egg',
  '2: Sniffer Egg',
  '2: Dead Tube Coral Block',
  '2: Dead Brain Coral Block',
  '2: Dead Bubble Coral Block',
  '2: Dead Fire Coral Block',
  '2: Dead Horn Coral Block',
  '2: Tube Coral Block',
  '2: Brain Coral Block',
  '2: Bubble Coral Block',
  '2: Fire Coral Block',
  '2: Horn Coral Block',
  '2: Tube Coral',
  '2: Brain Coral',
  '2: Bubble Coral',
  '2: Fire Coral',
  '2: Horn Coral',
  '2: Dead Brain Coral',
  '2: Dead Bubble Coral',
  '2: Dead Fire Coral',
  '2: Dead Horn Coral',
  '2: Dead Tube Coral',
  '2: Tube Coral Fan',
  '2: Brain Coral Fan',
  '2: Bubble Coral Fan',
  '2: Fire Coral Fan',
  '2: Horn Coral Fan',
  '2: Dead Tube Coral Fan',
  '2: Dead Brain Coral Fan',
  '2: Dead Bubble Coral Fan',
  '2: Dead Fire Coral Fan',
  '2: Dead Horn Coral Fan',
  '2: Blue Ice',
  '3: Conduit',
  '0: Polished Granite Stairs',
  '0: Smooth Red Sandstone Stairs',
  '0: Mossy Stone Brick Stairs',
  '0: Polished Diorite Stairs',
  '0: Mossy Cobblestone Stairs',
  '0: End Stone Brick Stairs',
  '0: Stone Stairs',
  '0: Smooth Sandstone Stairs',
  '0: Smooth Quartz Stairs',
  '0: Granite Stairs',
  '0: Andesite Stairs',
  '0: Red Nether Brick Stairs',
  '0: Polished Andesite Stairs',
  '0: Diorite Stairs',
  '0: Cobbled Deepslate Stairs',
  '0: Polished Deepslate Stairs',
  '0: Deepslate Brick Stairs',
  '0: Deepslate Tile Stairs',
  '0: Polished Granite Slab',
  '0: Smooth Red Sandstone Slab',
  '0: Mossy Stone Brick Slab',
  '0: Polished Diorite Slab',
  '0: Mossy Cobblestone Slab',
  '0: End Stone Brick Slab',
  '0: Smooth Sandstone Slab',
  '0: Smooth Quartz Slab',
  '0: Granite Slab',
  '0: Andesite Slab',
  '0: Red Nether Brick Slab',
  '0: Polished Andesite Slab',
  '0: Diorite Slab',
  '0: Cobbled Deepslate Slab',
  '0: Polished Deepslate Slab',
  '0: Deepslate Brick Slab',
  '0: Deepslate Tile Slab',
  '3: Scaffolding',
  '48: Redstone',
  '34: Redstone Torch',
  '04: Redstone Block',
  '4: Repeater',
  '4: Comparator',
  '4: Piston',
  '4: Sticky Piston',
  '24: Slime Block',
  '24: Honey Block',
  '4: Observer',
  '4: Hopper',
  '4: Dispenser',
  '4: Dropper',
  '34: Lectern',
  '4: Target',
  '4: Lever',
  '34: Lightning Rod',
  '4: Daylight Detector',
  '24: Sculk Sensor',
  '4: Calibrated Sculk Sensor',
  '4: Tripwire Hook',
  '4: Trapped Chest',
  '46: Tnt',
  '34: Redstone Lamp',
  '34: Note Block',
  '04: Stone Button',
  '0: Polished Blackstone Button',
  '04: Oak Button',
  '0: Spruce Button',
  '0: Birch Button',
  '0: Jungle Button',
  '0: Acacia Button',
  '0: Cherry Button',
  '0: Dark Oak Button',
  '0: Mangrove Button',
  '0: Bamboo Button',
  '0: Crimson Button',
  '0: Warped Button',
  '04: Stone Pressure Plate',
  '0: Polished Blackstone Pressure Plate',
  '04: Light Weighted Pressure Plate',
  '04: Heavy Weighted Pressure Plate',
  '04: Oak Pressure Plate',
  '0: Spruce Pressure Plate',
  '0: Birch Pressure Plate',
  '0: Jungle Pressure Plate',
  '0: Acacia Pressure Plate',
  '0: Cherry Pressure Plate',
  '0: Dark Oak Pressure Plate',
  '0: Mangrove Pressure Plate',
  '0: Bamboo Pressure Plate',
  '0: Crimson Pressure Plate',
  '0: Warped Pressure Plate',
  '04: Iron Door',
  '04: Oak Door',
  '0: Spruce Door',
  '0: Birch Door',
  '0: Jungle Door',
  '0: Acacia Door',
  '0: Cherry Door',
  '0: Dark Oak Door',
  '0: Mangrove Door',
  '0: Bamboo Door',
  '0: Crimson Door',
  '0: Warped Door',
  '04: Iron Trapdoor',
  '04: Oak Trapdoor',
  '0: Spruce Trapdoor',
  '0: Birch Trapdoor',
  '0: Jungle Trapdoor',
  '0: Acacia Trapdoor',
  '0: Cherry Trapdoor',
  '0: Dark Oak Trapdoor',
  '0: Mangrove Trapdoor',
  '0: Bamboo Trapdoor',
  '0: Crimson Trapdoor',
  '0: Warped Trapdoor',
  '04: Oak Fence Gate',
  '0: Spruce Fence Gate',
  '0: Birch Fence Gate',
  '0: Jungle Fence Gate',
  '0: Acacia Fence Gate',
  '0: Cherry Fence Gate',
  '0: Dark Oak Fence Gate',
  '0: Mangrove Fence Gate',
  '0: Bamboo Fence Gate',
  '0: Crimson Fence Gate',
  '0: Warped Fence Gate',
  '45: Powered Rail',
  '45: Detector Rail',
  '45: Rail',
  '45: Activator Rail',
  '5: Saddle',
  '45: Minecart',
  '45: Chest Minecart',
  '45: Furnace Minecart',
  '45: Tnt Minecart',
  '45: Hopper Minecart',
  '5: Carrot On A Stick',
  '5: Warped Fungus On A Stick',
  '5: Elytra',
  '5: Oak Boat',
  '45: Oak Chest Boat',
  '5: Spruce Boat',
  '5: Spruce Chest Boat',
  '5: Birch Boat',
  '5: Birch Chest Boat',
  '5: Jungle Boat',
  '5: Jungle Chest Boat',
  '5: Acacia Boat',
  '5: Acacia Chest Boat',
  '5: Cherry Boat',
  '5: Cherry Chest Boat',
  '5: Dark Oak Boat',
  '5: Dark Oak Chest Boat',
  '5: Mangrove Boat',
  '5: Mangrove Chest Boat',
  '5: Bamboo Raft',
  '45: Bamboo Chest Raft',
  ': Structure Block',
  ': Jigsaw',
  '68: Turtle Helmet',
  '8: Scute',
  '5: Flint And Steel',
  '7: Apple',
  '6: Bow',
  '6: Arrow',
  '8: Coal',
  '8: Charcoal',
  '8: Diamond',
  '8: Emerald',
  '8: Lapis Lazuli',
  '8: Quartz',
  '8: Amethyst Shard',
  '8: Raw Iron',
  '8: Iron Ingot',
  '8: Raw Copper',
  '8: Copper Ingot',
  '8: Raw Gold',
  '8: Gold Ingot',
  '8: Netherite Ingot',
  '8: Netherite Scrap',
  '6: Wooden Sword',
  '5: Wooden Shovel',
  '5: Wooden Pickaxe',
  '56: Wooden Axe',
  '5: Wooden Hoe',
  '6: Stone Sword',
  '5: Stone Shovel',
  '5: Stone Pickaxe',
  '56: Stone Axe',
  '5: Stone Hoe',
  '6: Golden Sword',
  '5: Golden Shovel',
  '5: Golden Pickaxe',
  '56: Golden Axe',
  '5: Golden Hoe',
  '6: Iron Sword',
  '5: Iron Shovel',
  '5: Iron Pickaxe',
  '56: Iron Axe',
  '5: Iron Hoe',
  '6: Diamond Sword',
  '5: Diamond Shovel',
  '5: Diamond Pickaxe',
  '56: Diamond Axe',
  '5: Diamond Hoe',
  '6: Netherite Sword',
  '5: Netherite Shovel',
  '5: Netherite Pickaxe',
  '56: Netherite Axe',
  '5: Netherite Hoe',
  '8: Stick',
  '8: Bowl',
  '7: Mushroom Stew',
  '48: String',
  '8: Feather',
  '8: Gunpowder',
  '2: Wheat Seeds',
  '8: Wheat',
  '7: Bread',
  '6: Leather Helmet',
  '6: Leather Chestplate',
  '6: Leather Leggings',
  '6: Leather Boots',
  '6: Chainmail Helmet',
  '6: Chainmail Chestplate',
  '6: Chainmail Leggings',
  '6: Chainmail Boots',
  '6: Iron Helmet',
  '6: Iron Chestplate',
  '6: Iron Leggings',
  '6: Iron Boots',
  '6: Diamond Helmet',
  '6: Diamond Chestplate',
  '6: Diamond Leggings',
  '6: Diamond Boots',
  '6: Golden Helmet',
  '6: Golden Chestplate',
  '6: Golden Leggings',
  '6: Golden Boots',
  '6: Netherite Helmet',
  '6: Netherite Chestplate',
  '6: Netherite Leggings',
  '6: Netherite Boots',
  '8: Flint',
  '7: Porkchop',
  '7: Cooked Porkchop',
  '3: Painting',
  '7: Golden Apple',
  '7: Enchanted Golden Apple',
  '3: Oak Sign',
  '3: Spruce Sign',
  '3: Birch Sign',
  '3: Jungle Sign',
  '3: Acacia Sign',
  '3: Cherry Sign',
  '3: Dark Oak Sign',
  '3: Mangrove Sign',
  '3: Bamboo Sign',
  '3: Crimson Sign',
  '3: Warped Sign',
  '3: Oak Hanging Sign',
  '3: Spruce Hanging Sign',
  '3: Birch Hanging Sign',
  '3: Jungle Hanging Sign',
  '3: Acacia Hanging Sign',
  '3: Cherry Hanging Sign',
  '3: Dark Oak Hanging Sign',
  '3: Mangrove Hanging Sign',
  '3: Bamboo Hanging Sign',
  '3: Crimson Hanging Sign',
  '3: Warped Hanging Sign',
  '5: Bucket',
  '5: Water Bucket',
  '5: Lava Bucket',
  '5: Powder Snow Bucket',
  '68: Snowball',
  '8: Leather',
  '57: Milk Bucket',
  '5: Pufferfish Bucket',
  '5: Salmon Bucket',
  '5: Cod Bucket',
  '5: Tropical Fish Bucket',
  '5: Axolotl Bucket',
  '5: Tadpole Bucket',
  '8: Brick',
  '8: Clay Ball',
  '2: Dried Kelp Block',
  '8: Paper',
  '8: Book',
  '8: Slime Ball',
  '68: Egg',
  '5: Compass',
  '5: Recovery Compass',
  ': Bundle',
  '5: Fishing Rod',
  '5: Clock',
  '5: Spyglass',
  '8: Glowstone Dust',
  '7: Cod',
  '7: Salmon',
  '7: Tropical Fish',
  '78: Pufferfish',
  '7: Cooked Cod',
  '7: Cooked Salmon',
  '8: Ink Sac',
  '8: Glow Ink Sac',
  '2: Cocoa Beans',
  '8: White Dye',
  '8: Orange Dye',
  '8: Magenta Dye',
  '8: Light Blue Dye',
  '8: Yellow Dye',
  '8: Lime Dye',
  '8: Pink Dye',
  '8: Gray Dye',
  '8: Light Gray Dye',
  '8: Cyan Dye',
  '8: Purple Dye',
  '8: Blue Dye',
  '8: Brown Dye',
  '8: Green Dye',
  '8: Red Dye',
  '8: Black Dye',
  '58: Bone Meal',
  '8: Bone',
  '8: Sugar',
  '7: Cake',
  '13: White Bed',
  '13: Orange Bed',
  '13: Magenta Bed',
  '13: Light Blue Bed',
  '13: Yellow Bed',
  '13: Lime Bed',
  '13: Pink Bed',
  '13: Gray Bed',
  '13: Light Gray Bed',
  '13: Cyan Bed',
  '13: Purple Bed',
  '13: Blue Bed',
  '13: Brown Bed',
  '13: Green Bed',
  '13: Red Bed',
  '13: Black Bed',
  '7: Cookie',
  '5: Filled Map',
  '5: Shears',
  '7: Melon Slice',
  '7: Dried Kelp',
  '2: Pumpkin Seeds',
  '2: Melon Seeds',
  '7: Beef',
  '7: Cooked Beef',
  '7: Chicken',
  '7: Cooked Chicken',
  '7: Rotten Flesh',
  '58: Ender Pearl',
  '8: Blaze Rod',
  '8: Ghast Tear',
  '8: Gold Nugget',
  '28: Nether Wart',
  '7: Potion of Water',
  '7: Potion of Mundane',
  '7: Potion of Thick',
  '7: Potion of Awkward',
  '7: Potion of Night Vision (3:00)',
  '7: Potion of Night Vision (8:00)',
  '7: Potion of Invisibility (3:00)',
  '7: Potion of Invisibility (8:00)',
  '7: Potion of Leaping (3:00)',
  '7: Potion of Leaping (8:00)',
  '7: Potion of Leaping II (1:30)',
  '7: Potion of Fire Resistance (3:00)',
  '7: Potion of Fire Resistance (8:00)',
  '7: Potion of Swiftness (3:00)',
  '7: Potion of Swiftness (8:00)',
  '7: Potion of Swiftness II (1:30)',
  '7: Potion of Slowness (1:30)',
  '7: Potion of Slowness (4:00)',
  '7: Potion of Slowness IV (0:20)',
  '7: Potion of Turtle Master (0:20)',
  '7: Potion of Turtle Master (0:40)',
  '7: Potion of Turtle Master IV (0:20)',
  '7: Potion of Water Breathing (3:00)',
  '7: Potion of Water Breathing (8:00)',
  '7: Potion of Healing',
  '7: Potion of Healing II',
  '7: Potion of Harming',
  '7: Potion of Harming II',
  '7: Potion of Poison (0:45)',
  '7: Potion of Poison (1:30)',
  '7: Potion of Poison II (0:22)',
  '7: Potion of Regeneration (0:45)',
  '7: Potion of Regeneration (1:30)',
  '7: Potion of Regeneration II (0:22)',
  '7: Potion of Strength (3:00)',
  '7: Potion of Strength (8:00)',
  '7: Potion of Strength II (1:30)',
  '7: Potion of Weakness (1:30)',
  '7: Potion of Weakness (4:00)',
  '7: Potion of Luck',
  '7: Potion of Slow Falling (1:30)',
  '7: Potion of Slow Falling (4:00)',
  '8: Glass Bottle',
  '78: Spider Eye',
  '8: Fermented Spider Eye',
  '8: Blaze Powder',
  '8: Magma Cream',
  '3: Brewing Stand',
  '34: Cauldron',
  '358: Ender Eye',
  '8: Glistering Melon Slice',
  ': Allay Spawn Egg',
  ': Axolotl Spawn Egg',
  ': Bat Spawn Egg',
  ': Bee Spawn Egg',
  ': Blaze Spawn Egg',
  ': Cat Spawn Egg',
  ': Camel Spawn Egg',
  ': Cave Spider Spawn Egg',
  ': Chicken Spawn Egg',
  ': Cod Spawn Egg',
  ': Cow Spawn Egg',
  ': Creeper Spawn Egg',
  ': Dolphin Spawn Egg',
  ': Donkey Spawn Egg',
  ': Drowned Spawn Egg',
  ': Elder Guardian Spawn Egg',
  ': Ender Dragon Spawn Egg',
  ': Enderman Spawn Egg',
  ': Endermite Spawn Egg',
  ': Evoker Spawn Egg',
  ': Fox Spawn Egg',
  ': Frog Spawn Egg',
  ': Ghast Spawn Egg',
  ': Glow Squid Spawn Egg',
  ': Goat Spawn Egg',
  ': Guardian Spawn Egg',
  ': Hoglin Spawn Egg',
  ': Horse Spawn Egg',
  ': Husk Spawn Egg',
  ': Iron Golem Spawn Egg',
  ': Llama Spawn Egg',
  ': Magma Cube Spawn Egg',
  ': Mooshroom Spawn Egg',
  ': Mule Spawn Egg',
  ': Ocelot Spawn Egg',
  ': Panda Spawn Egg',
  ': Parrot Spawn Egg',
  ': Phantom Spawn Egg',
  ': Pig Spawn Egg',
  ': Piglin Spawn Egg',
  ': Piglin Brute Spawn Egg',
  ': Pillager Spawn Egg',
  ': Polar Bear Spawn Egg',
  ': Pufferfish Spawn Egg',
  ': Rabbit Spawn Egg',
  ': Ravager Spawn Egg',
  ': Salmon Spawn Egg',
  ': Sheep Spawn Egg',
  ': Shulker Spawn Egg',
  ': Silverfish Spawn Egg',
  ': Skeleton Spawn Egg',
  ': Skeleton Horse Spawn Egg',
  ': Slime Spawn Egg',
  ': Sniffer Spawn Egg',
  ': Snow Golem Spawn Egg',
  ': Spider Spawn Egg',
  ': Squid Spawn Egg',
  ': Stray Spawn Egg',
  ': Strider Spawn Egg',
  ': Tadpole Spawn Egg',
  ': Trader Llama Spawn Egg',
  ': Tropical Fish Spawn Egg',
  ': Turtle Spawn Egg',
  ': Vex Spawn Egg',
  ': Villager Spawn Egg',
  ': Vindicator Spawn Egg',
  ': Wandering Trader Spawn Egg',
  ': Warden Spawn Egg',
  ': Witch Spawn Egg',
  ': Wither Spawn Egg',
  ': Wither Skeleton Spawn Egg',
  ': Wolf Spawn Egg',
  ': Zoglin Spawn Egg',
  ': Zombie Spawn Egg',
  ': Zombie Horse Spawn Egg',
  ': Zombie Villager Spawn Egg',
  ': Zombified Piglin Spawn Egg',
  '8: Experience Bottle',
  '58: Fire Charge',
  '5: Writable Book',
  '5: Written Book',
  '3: Item Frame',
  '3: Glow Item Frame',
  '3: Flower Pot',
  '7: Carrot',
  '7: Potato',
  '7: Baked Potato',
  '7: Poisonous Potato',
  '5: Map',
  '78: Golden Carrot',
  '3: Skeleton Skull',
  '3: Wither Skeleton Skull',
  '3: Player Head',
  '3: Zombie Head',
  '3: Creeper Head',
  '3: Dragon Head',
  '3: Piglin Head',
  '8: Nether Star',
  '7: Pumpkin Pie',
  '56: Firework Rocket',
  '8: Firework Star',
  '8: Enchanted Book',
  '8: Nether Brick',
  '8: Prismarine Shard',
  '8: Prismarine Crystals',
  '7: Rabbit',
  '7: Cooked Rabbit',
  '7: Rabbit Stew',
  '8: Rabbit Foot',
  '8: Rabbit Hide',
  '34: Armor Stand',
  '6: Iron Horse Armor',
  '6: Golden Horse Armor',
  '6: Diamond Horse Armor',
  '6: Leather Horse Armor',
  '5: Lead',
  '5: Name Tag',
  ': Command Block Minecart',
  '7: Mutton',
  '7: Cooked Mutton',
  '13: White Banner',
  '13: Orange Banner',
  '13: Magenta Banner',
  '13: Light Blue Banner',
  '13: Yellow Banner',
  '13: Lime Banner',
  '13: Pink Banner',
  '13: Gray Banner',
  '13: Light Gray Banner',
  '13: Cyan Banner',
  '13: Purple Banner',
  '13: Blue Banner',
  '13: Brown Banner',
  '13: Green Banner',
  '13: Red Banner',
  '13: Black Banner',
  '36: End Crystal',
  '7: Chorus Fruit',
  '8: Popped Chorus Fruit',
  '2: Torchflower Seeds',
  '2: Pitcher Pod',
  '7: Beetroot',
  '2: Beetroot Seeds',
  '7: Beetroot Soup',
  '8: Dragon Breath',
  '7: Splash Potion of Water',
  '7: Splash Potion of Mundane',
  '7: Splash Potion of Thick',
  '7: Splash Potion of Awkward',
  '7: Splash Potion of Night Vision (3:00)',
  '7: Splash Potion of Night Vision (8:00)',
  '7: Splash Potion of Invisibility (3:00)',
  '7: Splash Potion of Invisibility (8:00)',
  '7: Splash Potion of Leaping (3:00)',
  '7: Splash Potion of Leaping (8:00)',
  '7: Splash Potion of Leaping II (1:30)',
  '7: Splash Potion of Fire Resistance (3:00)',
  '7: Splash Potion of Fire Resistance (8:00)',
  '7: Splash Potion of Swiftness (3:00)',
  '7: Splash Potion of Swiftness (8:00)',
  '7: Splash Potion of Swiftness II (1:30)',
  '7: Splash Potion of Slowness (1:30)',
  '7: Splash Potion of Slowness (4:00)',
  '7: Splash Potion of Slowness IV (0:20)',
  '7: Splash Potion of Turtle Master (0:20)',
  '7: Splash Potion of Turtle Master (0:40)',
  '7: Splash Potion of Turtle Master IV (0:20)',
  '7: Splash Potion of Water Breathing (3:00)',
  '7: Splash Potion of Water Breathing (8:00)',
  '7: Splash Potion of Healing',
  '7: Splash Potion of Healing II',
  '7: Splash Potion of Harming',
  '7: Splash Potion of Harming II',
  '7: Splash Potion of Poison (0:45)',
  '7: Splash Potion of Poison (1:30)',
  '7: Splash Potion of Poison II (0:22)',
  '7: Splash Potion of Regeneration (0:45)',
  '7: Splash Potion of Regeneration (1:30)',
  '7: Splash Potion of Regeneration II (0:22)',
  '7: Splash Potion of Strength (3:00)',
  '7: Splash Potion of Strength (8:00)',
  '7: Splash Potion of Strength II (1:30)',
  '7: Splash Potion of Weakness (1:30)',
  '7: Splash Potion of Weakness (4:00)',
  '7: Splash Potion of Luck',
  '7: Splash Potion of Slow Falling (1:30)',
  '7: Splash Potion of Slow Falling (4:00)',
  '6: Spectral Arrow',
  '6: Tipped Arrow of Water',
  '6: Tipped Arrow of Mundane',
  '6: Tipped Arrow of Thick',
  '6: Tipped Arrow of Awkward',
  '6: Tipped Arrow of Night Vision (3:00)',
  '6: Tipped Arrow of Night Vision (8:00)',
  '6: Tipped Arrow of Invisibility (3:00)',
  '6: Tipped Arrow of Invisibility (8:00)',
  '6: Tipped Arrow of Leaping (3:00)',
  '6: Tipped Arrow of Leaping (8:00)',
  '6: Tipped Arrow of Leaping II (1:30)',
  '6: Tipped Arrow of Fire Resistance (3:00)',
  '6: Tipped Arrow of Fire Resistance (8:00)',
  '6: Tipped Arrow of Swiftness (3:00)',
  '6: Tipped Arrow of Swiftness (8:00)',
  '6: Tipped Arrow of Swiftness II (1:30)',
  '6: Tipped Arrow of Slowness (1:30)',
  '6: Tipped Arrow of Slowness (4:00)',
  '6: Tipped Arrow of Slowness IV (0:20)',
  '6: Tipped Arrow of Turtle Master (0:20)',
  '6: Tipped Arrow of Turtle Master (0:40)',
  '6: Tipped Arrow of Turtle Master IV (0:20)',
  '6: Tipped Arrow of Water Breathing (3:00)',
  '6: Tipped Arrow of Water Breathing (8:00)',
  '6: Tipped Arrow of Healing',
  '6: Tipped Arrow of Healing II',
  '6: Tipped Arrow of Harming',
  '6: Tipped Arrow of Harming II',
  '6: Tipped Arrow of Poison (0:45)',
  '6: Tipped Arrow of Poison (1:30)',
  '6: Tipped Arrow of Poison II (0:22)',
  '6: Tipped Arrow of Regeneration (0:45)',
  '6: Tipped Arrow of Regeneration (1:30)',
  '6: Tipped Arrow of Regeneration II (0:22)',
  '6: Tipped Arrow of Strength (3:00)',
  '6: Tipped Arrow of Strength (8:00)',
  '6: Tipped Arrow of Strength II (1:30)',
  '6: Tipped Arrow of Weakness (1:30)',
  '6: Tipped Arrow of Weakness (4:00)',
  '6: Tipped Arrow of Luck',
  '6: Tipped Arrow of Slow Falling (1:30)',
  '6: Tipped Arrow of Slow Falling (4:00)',
  '7: Lingering Potion of Water',
  '7: Lingering Potion of Mundane',
  '7: Lingering Potion of Thick',
  '7: Lingering Potion of Awkward',
  '7: Lingering Potion of Night Vision (3:00)',
  '7: Lingering Potion of Night Vision (8:00)',
  '7: Lingering Potion of Invisibility (3:00)',
  '7: Lingering Potion of Invisibility (8:00)',
  '7: Lingering Potion of Leaping (3:00)',
  '7: Lingering Potion of Leaping (8:00)',
  '7: Lingering Potion of Leaping II (1:30)',
  '7: Lingering Potion of Fire Resistance (3:00)',
  '7: Lingering Potion of Fire Resistance (8:00)',
  '7: Lingering Potion of Swiftness (3:00)',
  '7: Lingering Potion of Swiftness (8:00)',
  '7: Lingering Potion of Swiftness II (1:30)',
  '7: Lingering Potion of Slowness (1:30)',
  '7: Lingering Potion of Slowness (4:00)',
  '7: Lingering Potion of Slowness IV (0:20)',
  '7: Lingering Potion of Turtle Master (0:20)',
  '7: Lingering Potion of Turtle Master (0:40)',
  '7: Lingering Potion of Turtle Master IV (0:20)',
  '7: Lingering Potion of Water Breathing (3:00)',
  '7: Lingering Potion of Water Breathing (8:00)',
  '7: Lingering Potion of Healing',
  '7: Lingering Potion of Healing II',
  '7: Lingering Potion of Harming',
  '7: Lingering Potion of Harming II',
  '7: Lingering Potion of Poison (0:45)',
  '7: Lingering Potion of Poison (1:30)',
  '7: Lingering Potion of Poison II (0:22)',
  '7: Lingering Potion of Regeneration (0:45)',
  '7: Lingering Potion of Regeneration (1:30)',
  '7: Lingering Potion of Regeneration II (0:22)',
  '7: Lingering Potion of Strength (3:00)',
  '7: Lingering Potion of Strength (8:00)',
  '7: Lingering Potion of Strength II (1:30)',
  '7: Lingering Potion of Weakness (1:30)',
  '7: Lingering Potion of Weakness (4:00)',
  '7: Lingering Potion of Luck',
  '7: Lingering Potion of Slow Falling (1:30)',
  '7: Lingering Potion of Slow Falling (4:00)',
  '6: Shield',
  '6: Totem of Undying',
  '8: Shulker Shell',
  '8: Iron Nugget',
  ': Knowledge Book',
  ': Debug Stick',
  '5: Music Disc 13',
  '5: Music Disc Cat',
  '5: Music Disc Blocks',
  '5: Music Disc Chirp',
  '5: Music Disc Far',
  '5: Music Disc Mall',
  '5: Music Disc Mellohi',
  '5: Music Disc Stal',
  '5: Music Disc Strad',
  '5: Music Disc Ward',
  '5: Music Disc 11',
  '5: Music Disc Wait',
  '5: Music Disc Otherside',
  '5: Music Disc Relic',
  '5: Music Disc 5',
  '5: Music Disc Pigstep',
  '8: Disc Fragment 5',
  '6: Trident',
  '8: Phantom Membrane',
  '8: Nautilus Shell',
  '8: Heart of The Sea',
  '6: Crossbow',
  '7: Suspicious Stew',
  '3: Loom',
  '8: Flower Banner Pattern',
  '8: Creeper Banner Pattern',
  '8: Skull Banner Pattern',
  '8: Mojang Banner Pattern',
  '8: Globe Banner Pattern',
  '8: Piglin Banner Pattern',
  '5: Goat Horn',
  '34: Composter',
  '34: Barrel',
  '3: Smoker',
  '3: Blast Furnace',
  '3: Cartography Table',
  '3: Fletching Table',
  '3: Grindstone',
  '3: Smithing Table',
  '3: Stonecutter',
  '34: Bell',
  '3: Lantern',
  '3: Soul Lantern',
  '27: Sweet Berries',
  '27: Glow Berries',
  '3: Campfire',
  '3: Soul Campfire',
  '23: Shroomlight',
  '8: Honeycomb',
  '23: Bee Nest',
  '3: Beehive',
  '7: Honey Bottle',
  '2: Honeycomb Block',
  '3: Lodestone',
  '23: Crying Obsidian',
  '02: Blackstone',
  '0: Blackstone Slab',
  '0: Blackstone Stairs',
  '0: Gilded Blackstone',
  '0: Polished Blackstone',
  '0: Polished Blackstone Slab',
  '0: Polished Blackstone Stairs',
  '0: Chiseled Polished Blackstone',
  '0: Polished Blackstone Bricks',
  '0: Polished Blackstone Brick Slab',
  '0: Polished Blackstone Brick Stairs',
  '0: Cracked Polished Blackstone Bricks',
  '3: Respawn Anchor',
  '13: Candle',
  '13: White Candle',
  '13: Orange Candle',
  '13: Magenta Candle',
  '13: Light Blue Candle',
  '13: Yellow Candle',
  '13: Lime Candle',
  '13: Pink Candle',
  '13: Gray Candle',
  '13: Light Gray Candle',
  '13: Cyan Candle',
  '13: Purple Candle',
  '13: Blue Candle',
  '13: Brown Candle',
  '13: Green Candle',
  '13: Red Candle',
  '13: Black Candle',
  '2: Small Amethyst Bud',
  '2: Medium Amethyst Bud',
  '2: Large Amethyst Bud',
  '2: Amethyst Cluster',
  '2: Pointed Dripstone',
  '23: Ochre Froglight',
  '23: Verdant Froglight',
  '23: Pearlescent Froglight',
  '2: Frogspawn',
  '8: Echo Shard',
  '5: Brush',
  '8: Netherite Upgrade Smithing Template',
  '8: Sentry Armor Trim Smithing Template',
  '8: Dune Armor Trim Smithing Template',
  '8: Coast Armor Trim Smithing Template',
  '8: Wild Armor Trim Smithing Template',
  '8: Ward Armor Trim Smithing Template',
  '8: Eye Armor Trim Smithing Template',
  '8: Vex Armor Trim Smithing Template',
  '8: Tide Armor Trim Smithing Template',
  '8: Snout Armor Trim Smithing Template',
  '8: Rib Armor Trim Smithing Template',
  '8: Spire Armor Trim Smithing Template',
  '8: Wayfinder Armor Trim Smithing Template',
  '8: Shaper Armor Trim Smithing Template',
  '8: Silence Armor Trim Smithing Template',
  '8: Raiser Armor Trim Smithing Template',
  '8: Host Armor Trim Smithing Template',
  '8: Angler Pottery Sherd',
  '8: Archer Pottery Sherd',
  '8: Arms Up Pottery Sherd',
  '8: Blade Pottery Sherd',
  '8: Brewer Pottery Sherd',
  '8: Burn Pottery Sherd',
  '8: Danger Pottery Sherd',
  '8: Explorer Pottery Sherd',
  '8: Friend Pottery Sherd',
  '8: Heart Pottery Sherd',
  '8: Heartbreak Pottery Sherd',
  '8: Howl Pottery Sherd',
  '8: Miner Pottery Sherd',
  '8: Mourner Pottery Sherd',
  '8: Plenty Pottery Sherd',
  '8: Prize Pottery Sherd',
  '8: Sheaf Pottery Sherd',
  '8: Shelter Pottery Sherd',
  '8: Skull Pottery Sherd',
  '8: Snort Pottery Sherd',
];
