export const items = [
  '4: Acacia Boat',
  '4: Acacia Boat with Chest',
  '3: Acacia Button',
  '3: Acacia Door',
  '2: Acacia Fence',
  '3: Acacia Fence Gate',
  '2: Acacia Leaves',
  '1: Acacia Log',
  '1: Acacia Planks',
  '3: Acacia Pressure Plate',
  '2: Acacia Sapling',
  '2: Acacia Sign',
  '1: Acacia Slab',
  '1: Acacia Stairs',
  '3: Acacia Trapdoor',
  '1: Acacia Wood',
  '4: Activator Rail',
  '2: Allium',
  '1: Amethyst Block',
  '2: Amethyst Cluster',
  '5: Amethyst Shard',
  '1: Ancient Debris',
  '1: Andesite',
  '1: Andesite Slab',
  '1: Andesite Stairs',
  '2: Andesite Wall',
  '2: Anvil',
  '6: Apple',
  '2: Armor Stand',
  '8: Arrow',
  '2: Azalea',
  '2: Azalea Leaves',
  '2: Azure Bluet',
  '6: Baked Potato',
  '2: Bamboo',
  '5: Banner Pattern Creeper',
  '5: Banner Pattern Flower',
  '5: Banner Pattern Globe',
  '5: Banner Pattern Skull',
  '5: Banner Pattern Snout',
  '5: Banner Pattern Item',
  '2: Barrel',
  '1: Basalt',
  '5: Beacon',
  '2: Bee Nest',
  '2: Beehive',
  '6: Beetroot',
  '5: Beetroot Seeds',
  '6: Beetroot Soup',
  '2: Bell',
  '2: Big Dripleaf',
  '4: Birch Boat',
  '4: Birch Boat with Chest',
  '3: Birch Button',
  '3: Birch Door',
  '2: Birch Fence',
  '3: Birch Fence Gate',
  '2: Birch Leaves',
  '1: Birch Log',
  '1: Birch Planks',
  '3: Birch Pressure Plate',
  '2: Birch Sapling',
  '2: Birch Sign',
  '1: Birch Slab',
  '1: Birch Stairs',
  '3: Birch Trapdoor',
  '1: Birch Wood',
  '2: Black Banner',
  '2: Black Bed',
  '2: Black Candle',
  '2: Black Carpet',
  '1: Black Concrete',
  '1: Black Concrete Powder',
  '5: Black Dye',
  '2: Black Glazed Terracotta',
  '2: Black Shulker Box',
  '1: Black Stained Glass',
  '2: Black Stained Glass Pane',
  '1: Black Terracotta',
  '1: Black Wool',
  '1: Blackstone',
  '1: Blackstone Slab',
  '1: Blackstone Stairs',
  '2: Blackstone Wall',
  '2: Blast Furnace',
  '9: Blaze Powder',
  '5: Blaze Rod',
  '2: Blue Banner',
  '2: Blue Bed',
  '2: Blue Candle',
  '2: Blue Carpet',
  '1: Blue Concrete',
  '1: Blue Concrete Powder',
  '5: Blue Dye',
  '2: Blue Glazed Terracotta',
  '1: Blue Ice',
  '2: Blue Orchid',
  '2: Blue Shulker Box',
  '1: Blue Stained Glass',
  '2: Blue Stained Glass Pane',
  '1: Blue Terracotta',
  '1: Blue Wool',
  '5: Bone',
  '1: Bone Block',
  '5: Bone Meal',
  '5: Book',
  '5: Book and Quill',
  '1: Bookshelf',
  '5: Bottle o` Enchanting',
  '8: Bow',
  '5: Bowl',
  '2: Brain Coral',
  '1: Brain Coral Block',
  '2: Brain Coral Fan',
  '6: Bread',
  '9: Brewing Stand',
  '5: Brick',
  '1: Brick Slab',
  '1: Brick Stairs',
  '2: Brick Wall',
  '1: Bricks',
  '2: Brown Banner',
  '2: Brown Bed',
  '2: Brown Candle',
  '2: Brown Carpet',
  '1: Brown Concrete',
  '1: Brown Concrete Powder',
  '5: Brown Dye',
  '2: Brown Glazed Terracotta',
  '2: Brown Mushroom',
  '2: Brown Mushroom Block',
  '2: Brown Shulker Box',
  '1: Brown Stained Glass',
  '2: Brown Stained Glass Pane',
  '1: Brown Terracotta',
  '1: Brown Wool',
  '2: Bubble Coral',
  '1: Bubble Coral Block',
  '2: Bubble Coral Fan',
  '5: Bucket',
  '5: Bucket of Axolotl',
  '5: Bucket of Cod',
  '5: Bucket of Pufferfish',
  '5: Bucket of Salmon',
  '5: Bucket of Tadpole',
  '5: Bucket of Tropical Fish',
  '2: Cactus',
  '6: Cake',
  '1: Calcite',
  '2: Campfire',
  '2: Candle',
  '6: Carrot',
  '4: Carrot on a Stick',
  '2: Cartography Table',
  '1: Carved Pumpkin',
  '9: Cauldron',
  '2: Chain',
  '8: Chainmail Boots',
  '8: Chainmail Chestplate',
  '8: Chainmail Helmet',
  '8: Chainmail Leggings',
  '5: Charcoal',
  '2: Chest',
  '2: Chipped Anvil',
  '1: Chiseled Deepslate',
  '1: Chiseled Nether Bricks',
  '1: Chiseled Polished Blackstone',
  '1: Chiseled Quartz Block',
  '1: Chiseled Red Sandstone',
  '1: Chiseled Sandstone',
  '1: Chiseled Stone Bricks',
  '2: Chorus Flower',
  '5: Chorus Fruit',
  '1: Clay',
  '5: Clay Ball',
  '7: Clock',
  '5: Coal',
  '1: Coal Block',
  '1: Coal Ore',
  '1: Coarse Dirt',
  '1: Cobbled Deepslate',
  '1: Cobbled Deepslate Slab',
  '1: Cobbled Deepslate Stairs',
  '2: Cobbled Deepslate Wall',
  '1: Cobblestone',
  '1: Cobblestone Slab',
  '1: Cobblestone Stairs',
  '2: Cobblestone Wall',
  '2: Cobweb',
  '5: Cocoa Beans',
  '7: Compass',
  '2: Composter',
  '5: Conduit',
  '6: Cooked Chicken',
  '6: Cooked Cod',
  '6: Cooked Mutton',
  '6: Cooked Porkchop',
  '6: Cooked Rabbit',
  '6: Cooked Salmon',
  '6: Cookie',
  '1: Copper Block',
  '5: Copper Ingot',
  '1: Copper Ore',
  '2: Cornflower',
  '1: Cracked Deepslate Bricks',
  '1: Cracked Deepslate Tiles',
  '1: Cracked Nether Bricks',
  '1: Cracked Polished Blackstone Bricks',
  '1: Cracked Stone Bricks',
  '2: Crafting Table',
  '2: Creeper Head',
  '3: Crimson Button',
  '3: Crimson Door',
  '2: Crimson Fence',
  '3: Crimson Fence Gate',
  '2: Crimson Fungus',
  '1: Crimson Hyphae',
  '1: Crimson Nylium',
  '1: Crimson Planks',
  '3: Crimson Pressure Plate',
  '2: Crimson Roots',
  '2: Crimson Sign',
  '1: Crimson Slab',
  '1: Crimson Stairs',
  '1: Crimson Stem',
  '3: Crimson Trapdoor',
  '8: Crossbow',
  '1: Crying Obsidian',
  '1: Cut Copper',
  '1: Cut Copper Slab',
  '1: Cut Copper Stairs',
  '1: Cut Red Sandstone',
  '1: Cut Red Sandstone Slab',
  '1: Cut Sandstone',
  '1: Cut Sandstone Slab',
  '2: Cyan Banner',
  '2: Cyan Bed',
  '2: Cyan Candle',
  '2: Cyan Carpet',
  '1: Cyan Concrete',
  '1: Cyan Concrete Powder',
  '5: Cyan Dye',
  '2: Cyan Glazed Terracotta',
  '2: Cyan Shulker Box',
  '1: Cyan Stained Glass',
  '2: Cyan Stained Glass Pane',
  '1: Cyan Terracotta',
  '1: Cyan Wool',
  '2: Damaged Anvil',
  '2: Dandelion',
  '4: Dark Oak Boat',
  '4: Dark Oak Boat with Chest',
  '3: Dark Oak Button',
  '3: Dark Oak Door',
  '2: Dark Oak Fence',
  '3: Dark Oak Fence Gate',
  '2: Dark Oak Leaves',
  '1: Dark Oak Log',
  '1: Dark Oak Planks',
  '3: Dark Oak Pressure Plate',
  '2: Dark Oak Sapling',
  '2: Dark Oak Sign',
  '1: Dark Oak Slab',
  '1: Dark Oak Stairs',
  '3: Dark Oak Trapdoor',
  '1: Dark Oak Wood',
  '1: Dark Prismarine',
  '1: Dark Prismarine Slab',
  '1: Dark Prismarine Stairs',
  '3: Daylight Detector',
  '2: Dead Brain Coral',
  '1: Dead Brain Coral Block',
  '2: Dead Brain Coral Fan',
  '2: Dead Bubble Coral',
  '1: Dead Bubble Coral Block',
  '2: Dead Bubble Coral Fan',
  '2: Dead Bush',
  '2: Dead Fire Coral',
  '1: Dead Fire Coral Block',
  '2: Dead Fire Coral Fan',
  '2: Dead Horn Coral',
  '1: Dead Horn Coral Block',
  '2: Dead Horn Coral Fan',
  '2: Dead Tube Coral',
  '1: Dead Tube Coral Block',
  '2: Dead Tube Coral Fan',
  '1: Deepslate',
  '1: Deepslate Brick Slab',
  '1: Deepslate Brick Stairs',
  '2: Deepslate Brick Wall',
  '1: Deepslate Bricks',
  '1: Deepslate Coal Ore',
  '1: Deepslate Copper Ore',
  '1: Deepslate Diamond Ore',
  '1: Deepslate Emerald Ore',
  '1: Deepslate Gold Ore',
  '1: Deepslate Iron Ore',
  '1: Deepslate Lapis Lazuli Ore',
  '1: Deepslate Redstone Ore',
  '1: Deepslate Tile Slab',
  '1: Deepslate Tile Stairs',
  '2: Deepslate Tile Wall',
  '1: Deepslate Tiles',
  '4: Detector Rail',
  '5: Diamond',
  '7: Diamond Axe',
  '1: Diamond Block',
  '8: Diamond Boots',
  '8: Diamond Chestplate',
  '8: Diamond Helmet',
  '7: Diamond Hoe',
  '5: Diamond Horse Armor',
  '8: Diamond Leggings',
  '1: Diamond Ore',
  '7: Diamond Pickaxe',
  '7: Diamond Shovel',
  '8: Diamond Sword',
  '1: Diorite',
  '1: Diorite Slab',
  '1: Diorite Stairs',
  '2: Diorite Wall',
  '1: Dirt',
  '5: Disc Fragment',
  '3: Dispenser',
  '2: Dragon Egg',
  '2: Dragon Head',
  '9: Dragon`s Breath',
  '6: Dried Kelp',
  '1: Dried Kelp Block',
  '1: Dripstone Block',
  '3: Dropper',
  '5: Echo Shard',
  '5: Egg',
  '4: Elytra',
  '5: Emerald',
  '1: Emerald Block',
  '1: Emerald Ore',
  '5: Empty Map',
  '7: Enchanted Book',
  '6: Enchanted Golden Apple',
  '2: Enchanting Table',
  '2: End Crystal',
  '2: End Rod',
  '1: End Stone',
  '1: End Stone Brick Slab',
  '1: End Stone Brick Stairs',
  '2: End Stone Brick Wall',
  '1: End Stone Bricks',
  '2: Ender Chest',
  '5: Ender Pearl',
  '1: Exposed Copper Block',
  '1: Exposed Cut Copper',
  '1: Exposed Cut Copper Slab',
  '1: Exposed Cut Copper Stairs',
  '5: Eye of Ender',
  '5: Feather',
  '9: Fermented Spider Eye',
  '2: Fern',
  '5: Fire Charge',
  '2: Fire Coral',
  '1: Fire Coral Block',
  '2: Fire Coral Fan',
  '5: Firework Rocket',
  '5: Firework Star',
  '7: Fishing Rod',
  '2: Fletching Table',
  '5: Flint',
  '7: Flint and Steel',
  '2: Flower Pot',
  '2: Flowering Azalea',
  '2: Flowering Azalea Leaves',
  '2: Furnace',
  '9: Ghast Tear',
  '1: Gilded Blackstone',
  '1: Glass',
  '9: Glass Bottle',
  '2: Glass Pane',
  '9: Glistering Melon Slice',
  '6: Glow Berries',
  '5: Glow Ink Sac',
  '2: Glow Item Frame',
  '2: Glow Lichen',
  '1: Glowstone',
  '5: Glowstone Dust',
  '5: Goat Horn',
  '1: Gold Block',
  '5: Gold Ingot',
  '5: Gold Nugget',
  '1: Gold Ore',
  '6: Golden Apple',
  '7: Golden Axe',
  '8: Golden Boots',
  '9: Golden Carrot',
  '8: Golden Chestplate',
  '8: Golden Helmet',
  '7: Golden Hoe',
  '5: Golden Horse Armor',
  '8: Golden Leggings',
  '7: Golden Pickaxe',
  '7: Golden Shovel',
  '8: Golden Sword',
  '1: Granite',
  '1: Granite Slab',
  '1: Granite Stairs',
  '2: Granite Wall',
  '2: Grass',
  '1: Grass Block',
  '1: Gravel',
  '2: Gray Banner',
  '2: Gray Bed',
  '2: Gray Candle',
  '2: Gray Carpet',
  '1: Gray Concrete',
  '1: Gray Concrete Powder',
  '5: Gray Dye',
  '2: Gray Glazed Terracotta',
  '2: Gray Shulker Box',
  '1: Gray Stained Glass',
  '2: Gray Stained Glass Pane',
  '1: Gray Terracotta',
  '1: Gray Wool',
  '2: Green Banner',
  '2: Green Bed',
  '2: Green Candle',
  '2: Green Carpet',
  '1: Green Concrete',
  '1: Green Concrete Powder',
  '5: Green Dye',
  '2: Green Glazed Terracotta',
  '2: Green Shulker Box',
  '1: Green Stained Glass',
  '2: Green Stained Glass Pane',
  '1: Green Terracotta',
  '1: Green Wool',
  '2: Grindstone',
  '5: Gunpowder',
  '2: Hanging Roots',
  '1: Hay Bale',
  '5: Heart of the Sea',
  '3: Heavy Weighted Pressure Plate',
  '3: Honey Block',
  '6: Honey Bottle',
  '5: Honeycomb',
  '2: Honeycomb Block',
  '3: Hopper',
  '2: Horn Coral',
  '1: Horn Coral Block',
  '2: Horn Coral Fan',
  '1: Ice',
  '5: Ink Sac',
  '7: Iron Axe',
  '2: Iron Bars',
  '1: Iron Block',
  '8: Iron Boots',
  '8: Iron Chestplate',
  '3: Iron Door',
  '8: Iron Helmet',
  '7: Iron Hoe',
  '5: Iron Horse Armor',
  '5: Iron Ingot',
  '8: Iron Leggings',
  '5: Iron Nugget',
  '1: Iron Ore',
  '7: Iron Pickaxe',
  '7: Iron Shovel',
  '8: Iron Sword',
  '3: Iron Trapdoor',
  '2: Item Frame',
  '1: Jack o` Lantern',
  '2: Jukebox',
  '4: Jungle Boat',
  '4: Jungle Boat with Chest',
  '3: Jungle Button',
  '3: Jungle Door',
  '2: Jungle Fence',
  '3: Jungle Fence Gate',
  '2: Jungle Leaves',
  '1: Jungle Log',
  '1: Jungle Planks',
  '3: Jungle Pressure Plate',
  '2: Jungle Sapling',
  '2: Jungle Sign',
  '1: Jungle Slab',
  '1: Jungle Stairs',
  '3: Jungle Trapdoor',
  '1: Jungle Wood',
  '2: Kelp',
  '2: Ladder',
  '2: Lantern',
  '5: Lapis Lazuli',
  '1: Lapis Lazuli Block',
  '1: Lapis Lazuli Ore',
  '2: Large Amethyst Bud',
  '2: Large Fern',
  '5: Lava Bucket',
  '7: Lead',
  '5: Leather',
  '8: Leather Boots',
  '8: Leather Cap',
  '5: Leather Horse Armor',
  '8: Leather Pants',
  '8: Leather Tunic',
  '3: Lectern',
  '3: Lever',
  '2: Light Blue Banner',
  '2: Light Blue Bed',
  '2: Light Blue Candle',
  '2: Light Blue Carpet',
  '1: Light Blue Concrete',
  '1: Light Blue Concrete Powder',
  '5: Light Blue Dye',
  '2: Light Blue Glazed Terracotta',
  '2: Light Blue Shulker Box',
  '1: Light Blue Stained Glass',
  '2: Light Blue Stained Glass Pane',
  '1: Light Blue Terracotta',
  '1: Light Blue Wool',
  '2: Light Gray Banner',
  '2: Light Gray Bed',
  '2: Light Gray Candle',
  '2: Light Gray Carpet',
  '1: Light Gray Concrete',
  '1: Light Gray Concrete Powder',
  '5: Light Gray Dye',
  '2: Light Gray Glazed Terracotta',
  '2: Light Gray Shulker Box',
  '1: Light Gray Stained Glass',
  '2: Light Gray Stained Glass Pane',
  '1: Light Gray Terracotta',
  '1: Light Gray Wool',
  '3: Light Weighted Pressure Plate',
  '3: Lightning Rod',
  '2: Lilac',
  '2: Lily of the Valley',
  '2: Lily Pad',
  '2: Lime Banner',
  '2: Lime Bed',
  '2: Lime Candle',
  '2: Lime Carpet',
  '1: Lime Concrete',
  '1: Lime Concrete Powder',
  '5: Lime Dye',
  '2: Lime Glazed Terracotta',
  '2: Lime Shulker Box',
  '1: Lime Stained Glass',
  '2: Lime Stained Glass Pane',
  '1: Lime Terracotta',
  '1: Lime Wool',
  '9: Lingering Water Bottle',
  '2: Lodestone',
  '2: Loom',
  '2: Magenta Banner',
  '2: Magenta Bed',
  '2: Magenta Candle',
  '2: Magenta Carpet',
  '1: Magenta Concrete',
  '1: Magenta Concrete Powder',
  '5: Magenta Dye',
  '2: Magenta Glazed Terracotta',
  '2: Magenta Shulker Box',
  '1: Magenta Stained Glass',
  '2: Magenta Stained Glass Pane',
  '1: Magenta Terracotta',
  '1: Magenta Wool',
  '1: Magma Block',
  '9: Magma Cream',
  '4: Mangrove Boat',
  '4: Mangrove Boat with Chest',
  '3: Mangrove Button',
  '3: Mangrove Door',
  '2: Mangrove Fence',
  '3: Mangrove Fence Gate',
  '2: Mangrove Leaves',
  '1: Mangrove Log',
  '1: Mangrove Planks',
  '3: Mangrove Pressure Plate',
  '2: Mangrove Propagule',
  '1: Mangrove Roots',
  '2: Mangrove Sign',
  '1: Mangrove Slab',
  '1: Mangrove Stairs',
  '3: Mangrove Trapdoor',
  '1: Mangrove Wood',
  '5: Map',
  '2: Medium Amethyst Bud',
  '1: Melon',
  '5: Melon Seeds',
  '6: Melon Slice',
  '5: Milk Bucket',
  '4: Minecart',
  '4: Minecart with Chest',
  '4: Minecart with Furnace',
  '4: Minecart with Hopper',
  '4: Minecart with TNT',
  '2: Moss Block',
  '2: Moss Carpet',
  '1: Mossy Cobblestone',
  '1: Mossy Cobblestone Slab',
  '1: Mossy Cobblestone Stairs',
  '2: Mossy Cobblestone Wall',
  '1: Mossy Stone Brick Slab',
  '1: Mossy Stone Brick Stairs',
  '2: Mossy Stone Brick Wall',
  '1: Mossy Stone Bricks',
  '1: Mud',
  '1: Mud Brick Slab',
  '1: Mud Brick Stairs',
  '2: Mud Brick Wall',
  '1: Mud Bricks',
  '1: Muddy Mangrove Roots',
  '2: Mushroom Stem',
  '6: Mushroom Stew',
  '5: Music Disc 11',
  '5: Music Disc 13',
  '5: Music Disc 5',
  '5: Music Disc Blocks',
  '5: Music Disc Cat',
  '5: Music Disc Chirp',
  '5: Music Disc Far',
  '5: Music Disc Mall',
  '5: Music Disc Mellohi',
  '5: Music Disc Otherside',
  '5: Music Disc Pigstep',
  '5: Music Disc Stal',
  '5: Music Disc Strad',
  '5: Music Disc Wait',
  '5: Music Disc Ward',
  '1: Mycelium',
  '7: Name Tag',
  '5: Nautilus Shell',
  '5: Nether Brick',
  '2: Nether Brick Fence',
  '1: Nether Brick Slab',
  '1: Nether Brick Stairs',
  '2: Nether Brick Wall',
  '1: Nether Bricks',
  '1: Nether Gold Ore',
  '5: Nether Quartz',
  '1: Nether Quartz Ore',
  '2: Nether Sprouts',
  '5: Nether Star',
  '5: Nether Wart',
  '1: Nether Wart Block',
  '7: Netherite Axe',
  '1: Netherite Block',
  '8: Netherite Boots',
  '8: Netherite Chestplate',
  '8: Netherite Helmet',
  '7: Netherite Hoe',
  '5: Netherite Ingot',
  '8: Netherite Leggings',
  '7: Netherite Pickaxe',
  '5: Netherite Scrap',
  '7: Netherite Shovel',
  '8: Netherite Sword',
  '1: Netherrack',
  '3: Note Block',
  '4: Oak Boat',
  '4: Oak Boat with Chest',
  '3: Oak Button',
  '3: Oak Door',
  '2: Oak Fence',
  '3: Oak Fence Gate',
  '2: Oak Leaves',
  '1: Oak Log',
  '1: Oak Planks',
  '3: Oak Pressure Plate',
  '2: Oak Sapling',
  '2: Oak Sign',
  '1: Oak Slab',
  '1: Oak Stairs',
  '3: Oak Trapdoor',
  '1: Oak Wood',
  '3: Observer',
  '1: Obsidian',
  '2: Ochre Froglight',
  '2: Orange Banner',
  '2: Orange Bed',
  '2: Orange Candle',
  '2: Orange Carpet',
  '1: Orange Concrete',
  '1: Orange Concrete Powder',
  '5: Orange Dye',
  '2: Orange Glazed Terracotta',
  '2: Orange Shulker Box',
  '1: Orange Stained Glass',
  '2: Orange Stained Glass Pane',
  '1: Orange Terracotta',
  '2: Orange Tulip',
  '1: Orange Wool',
  '2: Oxeye Daisy',
  '1: Oxidized Copper Block',
  '1: Oxidized Cut Copper',
  '1: Oxidized Cut Copper Slab',
  '1: Oxidized Cut Copper Stairs',
  '1: Packed Ice',
  '1: Packed Mud',
  '2: Painting',
  '5: Paper',
  '2: Pearlescent Froglight',
  '2: Peony',
  '9: Phantom Membrane',
  '2: Pink Banner',
  '2: Pink Bed',
  '2: Pink Candle',
  '2: Pink Carpet',
  '1: Pink Concrete',
  '1: Pink Concrete Powder',
  '5: Pink Dye',
  '2: Pink Glazed Terracotta',
  '2: Pink Shulker Box',
  '1: Pink Stained Glass',
  '2: Pink Stained Glass Pane',
  '1: Pink Terracotta',
  '2: Pink Tulip',
  '1: Pink Wool',
  '3: Piston',
  '1: Podzol',
  '2: Pointed Dripstone',
  '6: Poisonous Potato',
  '1: Polished Andesite',
  '1: Polished Andesite Slab',
  '1: Polished Andesite Stairs',
  '1: Polished Basalt',
  '1: Polished Blackstone',
  '1: Polished Blackstone Brick Slab',
  '1: Polished Blackstone Brick Stairs',
  '2: Polished Blackstone Brick Wall',
  '1: Polished Blackstone Bricks',
  '3: Polished Blackstone Button',
  '3: Polished Blackstone Pressure Plate',
  '1: Polished Blackstone Slab',
  '1: Polished Blackstone Stairs',
  '2: Polished Blackstone Wall',
  '1: Polished Deepslate',
  '1: Polished Deepslate Slab',
  '1: Polished Deepslate Stairs',
  '2: Polished Deepslate Wall',
  '1: Polished Diorite',
  '1: Polished Diorite Slab',
  '1: Polished Diorite Stairs',
  '1: Polished Granite',
  '1: Polished Granite Slab',
  '1: Polished Granite Stairs',
  '5: Popped Chorus Fruit',
  '2: Poppy',
  '6: Potato',
  '5: Powder Snow Bucket',
  '4: Powered Rail',
  '1: Prismarine',
  '1: Prismarine Brick Slab',
  '1: Prismarine Brick Stairs',
  '1: Prismarine Bricks',
  '5: Prismarine Crystals',
  '5: Prismarine Shard',
  '1: Prismarine Slab',
  '1: Prismarine Stairs',
  '2: Prismarine Wall',
  '6: Pufferfish',
  '1: Pumpkin',
  '6: Pumpkin Pie',
  '5: Pumpkin Seeds',
  '2: Purple Banner',
  '2: Purple Bed',
  '2: Purple Candle',
  '2: Purple Carpet',
  '1: Purple Concrete',
  '1: Purple Concrete Powder',
  '5: Purple Dye',
  '2: Purple Glazed Terracotta',
  '2: Purple Shulker Box',
  '1: Purple Stained Glass',
  '2: Purple Stained Glass Pane',
  '1: Purple Terracotta',
  '1: Purple Wool',
  '1: Purpur Block',
  '1: Purpur Pillar',
  '1: Purpur Slab',
  '1: Purpur Stairs',
  '1: Quartz Block',
  '1: Quartz Bricks',
  '1: Quartz Pillar',
  '1: Quartz Slab',
  '1: Quartz Stairs',
  '5: Rabbit Hide',
  '6: Rabbit Stew',
  '9: Rabbit`s Foot',
  '4: Rail',
  '6: Raw Beef',
  '6: Raw Chicken',
  '6: Raw Cod',
  '5: Raw Copper',
  '1: Raw Copper Block',
  '5: Raw Gold',
  '1: Raw Gold Block',
  '5: Raw Iron',
  '1: Raw Iron Block',
  '6: Raw Mutton',
  '6: Raw Porkchop',
  '6: Raw Rabbit',
  '6: Raw Salmon',
  '7: Recovery Compass',
  '2: Red Banner',
  '2: Red Bed',
  '2: Red Candle',
  '2: Red Carpet',
  '1: Red Concrete',
  '1: Red Concrete Powder',
  '5: Red Dye',
  '2: Red Glazed Terracotta',
  '2: Red Mushroom',
  '2: Red Mushroom Block',
  '1: Red Nether Brick Slab',
  '1: Red Nether Brick Stairs',
  '2: Red Nether Brick Wall',
  '1: Red Nether Bricks',
  '1: Red Sand',
  '1: Red Sandstone',
  '1: Red Sandstone Slab',
  '1: Red Sandstone Stairs',
  '2: Red Sandstone Wall',
  '2: Red Shulker Box',
  '1: Red Stained Glass',
  '2: Red Stained Glass Pane',
  '1: Red Terracotta',
  '2: Red Tulip',
  '1: Red Wool',
  '3: Redstone Block',
  '3: Redstone Comparator',
  '3: Redstone Dust',
  '3: Redstone Lamp',
  '1: Redstone Ore',
  '3: Redstone Repeater',
  '3: Redstone Torch',
  '2: Respawn Anchor',
  '1: Rooted Dirt',
  '2: Rose Bush',
  '6: Rotten Flesh',
  '4: Saddle',
  '1: Sand',
  '1: Sandstone',
  '1: Sandstone Slab',
  '1: Sandstone Stairs',
  '2: Sandstone Wall',
  '2: Scaffolding',
  '2: Sculk',
  '2: Sculk Catalyst',
  '3: Sculk Sensor',
  '2: Sculk Shrieker',
  '2: Sculk Vein',
  '5: Scute',
  '1: Sea Lantern',
  '2: Sea Pickle',
  '2: Seagrass',
  '7: Shears',
  '8: Shield',
  '2: Shroomlight',
  '2: Shulker Box',
  '5: Shulker Shell',
  '2: Skeleton Skull',
  '3: Slime Block',
  '5: Slimeball',
  '2: Small Amethyst Bud',
  '2: Small Dripleaf',
  '2: Smiitem Table',
  '2: Smoker',
  '1: Smooth Basalt',
  '1: Smooth Quartz Block',
  '1: Smooth Quartz Slab',
  '1: Smooth Quartz Stairs',
  '1: Smooth Red Sandstone',
  '1: Smooth Red Sandstone Slab',
  '1: Smooth Red Sandstone Stairs',
  '1: Smooth Sandstone',
  '1: Smooth Sandstone Slab',
  '1: Smooth Sandstone Stairs',
  '1: Smooth Stone',
  '1: Smooth Stone Slab',
  '2: Snow',
  '1: Snow Block',
  '5: Snowball',
  '2: Soul Campfire',
  '2: Soul Lantern',
  '1: Soul Sand',
  '1: Soul Soil',
  '2: Soul Torch',
  '8: Spectral Arrow',
  '6: Spider Eye',
  '9: Splash Water Bottle',
  '1: Sponge',
  '2: Spore Blossom',
  '4: Spruce Boat',
  '4: Spruce Boat with Chest',
  '3: Spruce Button',
  '3: Spruce Door',
  '2: Spruce Fence',
  '3: Spruce Fence Gate',
  '2: Spruce Leaves',
  '1: Spruce Log',
  '1: Spruce Planks',
  '3: Spruce Pressure Plate',
  '2: Spruce Sapling',
  '2: Spruce Sign',
  '1: Spruce Slab',
  '1: Spruce Stairs',
  '3: Spruce Trapdoor',
  '1: Spruce Wood',
  '7: Spyglass',
  '6: Steak',
  '5: Stick',
  '3: Sticky Piston',
  '1: Stone',
  '7: Stone Axe',
  '1: Stone Brick Slab',
  '1: Stone Brick Stairs',
  '2: Stone Brick Wall',
  '1: Stone Bricks',
  '3: Stone Button',
  '7: Stone Hoe',
  '7: Stone Pickaxe',
  '3: Stone Pressure Plate',
  '7: Stone Shovel',
  '1: Stone Slab',
  '1: Stone Stairs',
  '8: Stone Sword',
  '2: Stonecutter',
  '5: String',
  '1: Stripped Acacia Log',
  '1: Stripped Acacia Wood',
  '1: Stripped Birch Log',
  '1: Stripped Birch Wood',
  '1: Stripped Crimson Hyphae',
  '1: Stripped Crimson Stem',
  '1: Stripped Dark Oak Log',
  '1: Stripped Dark Oak Wood',
  '1: Stripped Jungle Log',
  '1: Stripped Jungle Wood',
  '1: Stripped Mangrove Log',
  '1: Stripped Mangrove Wood',
  '1: Stripped Oak Log',
  '1: Stripped Oak Wood',
  '1: Stripped Spruce Log',
  '1: Stripped Spruce Wood',
  '1: Stripped Warped Hyphae',
  '1: Stripped Warped Stem',
  '5: Sugar',
  '2: Sugar Cane',
  '2: Sunflower',
  '6: Suspicious Stew',
  '6: Sweet Berries',
  '2: Tall Grass',
  '3: Target',
  '1: Terracotta',
  '1: Tinted Glass',
  '8: Tipped Arrow',
  '3: TNT',
  '2: Torch',
  '8: Totem of Undying',
  '3: Trapped Chest',
  '8: Trident',
  '3: Tripwire Hook',
  '6: Tropical Fish',
  '2: Tube Coral',
  '1: Tube Coral Block',
  '2: Tube Coral Fan',
  '1: Tuff',
  '5: Turtle Egg',
  '8: Turtle Shell',
  '2: Twisting Vines',
  '2: Verdant Froglight',
  '2: Vines',
  '3: Warped Button',
  '3: Warped Door',
  '2: Warped Fence',
  '3: Warped Fence Gate',
  '2: Warped Fungus',
  '4: Warped Fungus on a Stick',
  '1: Warped Hyphae',
  '1: Warped Nylium',
  '1: Warped Planks',
  '3: Warped Pressure Plate',
  '2: Warped Roots',
  '2: Warped Sign',
  '1: Warped Slab',
  '1: Warped Stairs',
  '1: Warped Stem',
  '3: Warped Trapdoor',
  '1: Warped Wart Block',
  '9: Water Bottle',
  '5: Water Bucket',
  '1: Waxed Copper Block',
  '1: Waxed Cut Copper',
  '1: Waxed Cut Copper Slab',
  '1: Waxed Cut Copper Stairs',
  '1: Waxed Exposed Copper Block',
  '1: Waxed Exposed Cut Copper',
  '1: Waxed Exposed Cut Copper Slab',
  '1: Waxed Exposed Cut Copper Stairs',
  '1: Waxed Oxidized Copper Block',
  '1: Waxed Oxidized Cut Copper',
  '1: Waxed Oxidized Cut Copper Slab',
  '1: Waxed Oxidized Cut Copper Stairs',
  '1: Waxed Weathered Copper Block',
  '1: Waxed Weathered Cut Copper',
  '1: Waxed Weathered Cut Copper Slab',
  '1: Waxed Weathered Cut Copper Stairs',
  '1: Weathered Copper Block',
  '1: Weathered Cut Copper',
  '1: Weathered Cut Copper Slab',
  '1: Weathered Cut Copper Stairs',
  '2: Weeping Vines',
  '1: Wet Sponge',
  '5: Wheat',
  '5: Wheat Seeds',
  '2: White Banner',
  '2: White Bed',
  '2: White Candle',
  '2: White Carpet',
  '1: White Concrete',
  '1: White Concrete Powder',
  '5: White Dye',
  '2: White Glazed Terracotta',
  '2: White Shulker Box',
  '1: White Stained Glass',
  '2: White Stained Glass Pane',
  '1: White Terracotta',
  '2: White Tulip',
  '1: White Wool',
  '2: Wither Rose',
  '2: Wither Skeleton Skull',
  '7: Wooden Axe',
  '7: Wooden Hoe',
  '7: Wooden Pickaxe',
  '7: Wooden Shovel',
  '8: Wooden Sword',
  '5: Written Book',
  '2: Yellow Banner',
  '2: Yellow Bed',
  '2: Yellow Candle',
  '2: Yellow Carpet',
  '1: Yellow Concrete',
  '1: Yellow Concrete Powder',
  '5: Yellow Dye',
  '2: Yellow Glazed Terracotta',
  '2: Yellow Shulker Box',
  '1: Yellow Stained Glass',
  '2: Yellow Stained Glass Pane',
  '1: Yellow Terracotta',
  '1: Yellow Wool',
  '2: Zombie Head',
];
