import { createApi } from '@reduxjs/toolkit/query/react';
import { baseQueryWithAuth } from './base.query';

export const emptyApi = createApi({
  baseQuery: baseQueryWithAuth,
  tagTypes: [
    'Auth',
    'User',
    'Message',
    'Friend',
    'Subscriber',
    'Report',
    'ReportView',
    'Attitude',
    'Annotation',
    'Article',
    'ArticleView',
    'Like',
    'Comment',
    'Card',
    'Exchange',
    'Payment',
    'Invoice',
    'City',
    'Shop',
    'Market',
    'Storage',
    'MarketTag',
    'StorageTag',
    'Store',
    'Cell',
    'Rent',
    'Lease',
    'Good',
    'Ware',
    'Product',
    'Order',
    'Delivery',
    'Trade',
    'Sale',
    'Task',
    'Plaint',
    'Answer',
    'Poll',
    'PollView',
    'Vote',
    'Discussion',
    'Rating',
  ],
  endpoints: () => ({}),
});
