export enum GoodError {
  ALREADY_EXPIRED = '400: Товар вже протерміновано',
  ALREADY_COMPLETED = '400: Товар вже завершено',
  ALREADY_BOUGHT = '400: Товар вже куплено',
  NOT_BOUGHT = '400: Товар не куплено',
  NOT_ENOUGH_AMOUNT = '400: Недостатня кількість товару',
  NOT_OWNER = '403: Ви не власник товару',
  CREATE_FAILED = '500: Не вдалося створити товар',
  EDIT_FAILED = '500: Не вдалося редагувати товар',
  UPDATE_FAILED = '500: Не вдалося оновити товар',
  COMPLETE_FAILED = '500: Не вдалося завершити товар',
  DELETE_FAILED = '500: Не вдалося видалити товар',
  BUY_FAILED = '500: Не вдалося купити товар',
  UNBUY_FAILED = '500: Не вдалося повернути товар',
}
