export enum CardError {
  ALREADY_HAS_ENOUGH = '400: User already has enough cards',
  NAME_ALREADY_USED = '400: Card name already used',
  ALREADY_ENOUGH_BALANCE = '400: Card already has enough balance',
  NOT_ENOUGH_BALANCE = '400: Card has not enough balance',
  ALREADY_IN_CARD = '400: User already in card',
  NOT_IN_CARD = '400: User not in card',
  OWNER = '400: User is card owner',
  NOT_OWNER = '403: You are not card owner',
  NOT_USER = '403: You are not card user',
  CREATE_FAILED = '500: Failed to create card',
  EDIT_FAILED = '500: Failed to edit card',
  ADD_USER_FAILED = '500: Failed to add card user',
  REMOVE_USER_FAILED = '500: Failed to remove card user',
  INCREASE_BALANCE_FAILED = '500: Failed to increase card balance',
  DECREASE_BALANCE_FAILED = '500: Failed to decrease card balance',
}
