export enum CardError {
  ALREADY_ENOUGH_BALANCE = '400: На карті достатньо балансу',
  NOT_ENOUGH_BALANCE = '400: На карті недостатньо балансу',
  ALREADY_IN_CARD = '400: Користувач вже в карті',
  NOT_IN_CARD = '400: Користувач не в карті',
  OWNER = '400: Користувач є власником карти',
  NOT_OWNER = '403: Ви не власник карти',
  NOT_USER = '403: Ви не користувач карти',
  CREATE_FAILED = '500: Не вдалося створити карту',
  EDIT_FAILED = '500: Не вдалося редагувати карту',
  ADD_USER_FAILED = '500: Не вдалося додати користувача в карту',
  REMOVE_USER_FAILED = '500: Не вдалося прибрати користувача з карти',
  INCREASE_BALANCE_FAILED = '500: Не вдалося збільшити баланс карти',
  DECREASE_BALANCE_FAILED = '500: Не вдалося зменшити баланс карти',
}
