export enum OrderError {
  ALREADY_EXPIRED = '400: Заказ уже просрочено',
  NOT_CREATED = '400: Заказ не создано',
  NOT_TAKEN = '400: Заказ не взято',
  NOT_EXECUTED = '400: Заказ не выполнено',
  NOT_COMPLETED = '400: Заказ не завершено',
  NOT_CUSTOMER = '403: Вы не заказчик заказа',
  NOT_EXECUTOR = '403: Вы не исполнитель заказа',
  CREATE_FAILED = '500: Не удалось создать заказ',
  TAKE_FAILED = '500: Не удалось взять заказ',
  UNTAKE_FAILED = '500: Не удалось отменить заказ',
  EXECUTE_FAILED = '500: Не удалось выполнить заказ',
  COMPLETE_FAILED = '500: Не удалось завершить заказ',
  DELETE_FAILED = '500: Не удалось удалить заказ',
  RATE_FAILED = '500: Не удалось оценить заказ',
}
